# Generated by Django 2.1.3 on 2018-11-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinderEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('localization', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DinderGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DinderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('localization', models.CharField(blank=True, max_length=100, null=True)),
                ('events', models.ManyToManyField(blank=True, null=True, to='dinder.DinderEvent')),
                ('groups', models.ManyToManyField(blank=True, null=True, to='dinder.DinderGroup')),
            ],
        ),
        migrations.AddField(
            model_name='dinderevent',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinder.DinderGroup'),
        ),
    ]
