# Generated by Django 2.1.3 on 2018-11-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinderEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DinderGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DinderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('events', models.ManyToManyField(to='dinder.DinderEvent')),
                ('groups', models.ManyToManyField(to='dinder.DinderGroup')),
            ],
        ),
        migrations.AddField(
            model_name='dinderevent',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinder.DinderGroup'),
        ),
    ]
