# Generated by Django 2.1.3 on 2018-11-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinderprofile',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, to='dinder.DinderEvent'),
        ),
        migrations.AlterField(
            model_name='dinderprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='dinder.DinderGroup'),
        ),
    ]
